// Contenido didáctico inicial: cada tema usa el mismo esquema para facilitar su ampliación.
window.UO_TEMAS = [
  {
    id: "introduccion-enfermeria",
    titulo: "Introducción a la Enfermería",
    unidad: "fundamentos",
    resumen: "La disciplina, el cuidado profesional y los principios éticos que orientan la práctica.",
    conceptos: ["Enfermería como disciplina y profesión", "Cuidado integral y centrado en la persona", "Ética, dignidad y respeto", "Colaboración interprofesional"],
    objetivo: "Explicar los conceptos esenciales de Enfermería e identificar cómo orientan un cuidado humano, responsable y respetuoso.",
    introduccion: "La Enfermería integra conocimiento científico, juicio profesional y una relación terapéutica con personas, familias y comunidades. Su práctica reconoce necesidades, promueve la salud y contribuye a una atención digna.",
    materiales: ["Guía de la asignatura", "Lecturas académicas indicadas por el equipo docente", "Cuaderno de reflexión"],
    pasos: ["Define con tus propias palabras qué significa cuidar.", "Relaciona las necesidades de una persona con un enfoque integral.", "Analiza un ejemplo de respeto a la dignidad, privacidad y autonomía.", "Contrasta tus conclusiones con el código profesional aplicable en tu contexto."],
    precauciones: ["Evita reducir el cuidado a la ejecución mecánica de tareas.", "Respeta creencias, preferencias, privacidad y contexto sociocultural.", "Consulta fuentes profesionales vigentes."],
    seguridad: ["Prioriza la dignidad, la identificación correcta y la comunicación clara.", "Reconoce el alcance de tu formación y solicita supervisión cuando corresponda."],
    errores: ["Confundir empatía con sustituir las decisiones de la persona.", "Usar definiciones descontextualizadas o no verificar su fuente."],
    evidencia: "Elabora un mapa conceptual de la disciplina y una reflexión breve sobre cómo el respeto y la ética se manifiestan en una situación de cuidado."
  },
  {
    id: "proceso-enfermeria",
    titulo: "Proceso de Enfermería",
    unidad: "fundamentos",
    resumen: "Método sistemático para organizar cuidados individualizados, evaluar resultados y documentar decisiones.",
    conceptos: ["Valoración", "Diagnóstico de Enfermería", "Planificación", "Ejecución", "Evaluación"],
    objetivo: "Describir las etapas del Proceso de Enfermería y explicar cómo se relacionan para orientar cuidados individualizados.",
    introduccion: "El Proceso de Enfermería es un método organizado y continuo de razonamiento clínico. Permite reunir información, reconocer respuestas humanas, planificar cuidados, llevarlos a cabo y evaluar sus resultados.",
    materiales: ["Caso académico anonimizado", "Formato de valoración indicado en el curso", "Taxonomías autorizadas por la asignatura, cuando correspondan"],
    pasos: ["Recopila datos pertinentes y distingue los subjetivos de los objetivos.", "Analiza la información sin omitir la perspectiva de la persona.", "Formula problemas o diagnósticos conforme al marco enseñado.", "Establece objetivos medibles e intervenciones individualizadas.", "Documenta acciones y evalúa resultados para revisar el plan."],
    precauciones: ["No inventes datos faltantes ni registres inferencias como hechos.", "Respeta el alcance profesional y las herramientas validadas por el curso."],
    seguridad: ["Verifica identidad, fuentes de información y cambios relevantes.", "Comunica oportunamente los hallazgos que requieren respuesta."],
    errores: ["Omitir la evaluación de resultados.", "Redactar objetivos vagos o intervenciones no relacionadas con los hallazgos.", "Copiar datos de otra persona o expediente."],
    evidencia: "Organiza un caso académico anonimizado en las etapas del proceso y justifica una meta y un indicador de evaluación."
  },
  {
    id: "expediente-clinico",
    titulo: "Expediente Clínico",
    unidad: "fundamentos",
    resumen: "Registro organizado, oportuno y confidencial de la información y la atención brindada.",
    conceptos: ["Continuidad de la atención", "Registro objetivo y cronológico", "Confidencialidad", "Responsabilidad documental"],
    objetivo: "Reconocer la función del expediente clínico y aplicar principios básicos de privacidad y documentación responsable.",
    introduccion: "El expediente clínico reúne información relacionada con la atención de salud. Su documentación facilita la comunicación y continuidad del cuidado, y debe proteger la privacidad y cumplir la normativa local vigente.",
    materiales: ["Formato docente de práctica sin identificadores reales", "Ejemplo de registro aprobado para estudio", "Normativa y política institucional aplicable"],
    pasos: ["Identifica propósito, formato y reglas locales del registro.", "Describe observaciones relevantes con lenguaje claro, preciso y objetivo.", "Ordena las anotaciones según la secuencia y los campos establecidos.", "Revisa la legibilidad y completa los datos que exige el formato académico.", "Protege el documento y comunica la información solo por canales autorizados."],
    precauciones: ["No utilices datos personales reales en ejercicios académicos.", "No alteres ni compartas registros sin autorización.", "Sigue las reglas locales para correcciones y firmas."],
    seguridad: ["Preserva confidencialidad y acceso autorizado.", "Distingue lo observado de lo referido y evita juicios de valor.", "Documenta en el momento establecido por la política institucional."],
    errores: ["Usar abreviaturas no autorizadas.", "Dejar campos incompletos, registrar opiniones como hechos o documentar antes de realizar una acción."],
    evidencia: "Redacta un ejemplo académico anonimizado con datos objetivos y señala cómo protegerías la confidencialidad."
  },
  {
    id: "signos-vitales",
    titulo: "Signos Vitales",
    unidad: "valoracion",
    resumen: "Medición e interpretación contextual de temperatura, pulso, respiración, presión arterial y otros parámetros indicados.",
    conceptos: ["Temperatura", "Pulso y frecuencia respiratoria", "Presión arterial", "Saturación de oxígeno según indicación", "Tendencias y contexto"],
    objetivo: "Identificar factores que afectan la medición de signos vitales y explicar cómo registrar y comunicar resultados de acuerdo con el protocolo.",
    introduccion: "Los signos vitales aportan información sobre el estado de una persona. Su significado depende del contexto, la técnica, el dispositivo, la edad, las condiciones clínicas y los rangos de referencia establecidos.",
    materiales: ["Equipo calibrado y apropiado para la persona", "Elementos de higiene según protocolo", "Formato de registro y referencia institucional"],
    pasos: ["Explica la valoración y prepara un entorno respetuoso.", "Confirma identidad según el protocolo y observa las condiciones pertinentes.", "Selecciona el equipo apropiado y verifica su funcionamiento.", "Realiza las mediciones conforme a la técnica enseñada y las instrucciones del dispositivo.", "Registra valores, hora, condiciones relevantes y equipo según el formato.", "Compara con la referencia del curso y comunica hallazgos que requieran atención."],
    precauciones: ["La guía académica no establece rangos universales ni sustituye juicio clínico.", "Considera las instrucciones del equipo y los factores que pueden alterar cada medición.", "Pide supervisión para interpretar cambios o valores preocupantes."],
    seguridad: ["Higieniza el equipo y aplica control de infecciones.", "Protege privacidad, comodidad y comunicación.", "Escala oportunamente hallazgos de acuerdo con la ruta institucional."],
    errores: ["Usar un brazalete o dispositivo inadecuado.", "Registrar un valor sin hora, contexto o verificación.", "Asumir que una medición aislada representa el estado completo."],
    evidencia: "Describe la técnica docente de un parámetro seleccionado, los factores que podrían modificarlo y cómo registrarías y comunicarías un resultado."
  },
  {
    id: "somatometria",
    titulo: "Somatometría",
    unidad: "valoracion",
    resumen: "Obtención y registro de medidas corporales con equipo apropiado, privacidad y técnica consistente.",
    conceptos: ["Peso", "Talla o longitud", "Índice calculado según contexto", "Tendencia y condiciones de medición"],
    objetivo: "Explicar los principios de una medición somatométrica consistente, respetuosa y contextualizada.",
    introduccion: "Las medidas corporales pueden apoyar la valoración cuando están indicadas. La técnica, el equipo, la condición de la persona y el contexto influyen en su interpretación.",
    materiales: ["Báscula y estadímetro apropiados y verificados", "Elementos de limpieza del equipo", "Formato de registro"],
    pasos: ["Explica el propósito y considera comodidad y privacidad.", "Comprueba el estado del equipo y la técnica indicada para la edad y situación.", "Solicita colaboración y realiza la medición con la posición indicada en la guía.", "Registra valor, unidades, fecha, hora y condiciones relevantes.", "Interpreta únicamente con la referencia clínica y docente correspondiente."],
    precauciones: ["Solicita ayuda para prevenir caídas o movilizaciones inseguras.", "No realices mediciones que expongan o incomoden innecesariamente a la persona."],
    seguridad: ["Verifica estabilidad del equipo y protección durante la posición requerida.", "Mantén higiene y limpieza según el protocolo."],
    errores: ["Omitir unidades o equipo utilizado.", "Comparar mediciones hechas con técnicas diferentes como si fueran equivalentes."],
    evidencia: "Prepara una lista de verificación de equipo, técnica, privacidad y registro para una medición de práctica."
  },
  {
    id: "exploracion-fisica",
    titulo: "Exploración Física",
    unidad: "valoracion",
    resumen: "Valoración sistemática que integra observación, entrevista y técnicas físicas dentro del alcance de formación.",
    conceptos: ["Inspección", "Palpación", "Percusión y auscultación según enseñanza", "Secuencia y comparación", "Consentimiento"],
    objetivo: "Distinguir el propósito de las técnicas de exploración física y reconocer condiciones esenciales de una valoración respetuosa y segura.",
    introduccion: "La exploración física complementa la entrevista y la revisión de antecedentes. La secuencia y las técnicas se aprenden de forma supervisada y se adaptan a la indicación, privacidad y condición de la persona.",
    materiales: ["Instrumentos adecuados y verificados", "Higiene de manos y elementos de protección según riesgo", "Espacio con privacidad"],
    pasos: ["Confirma propósito, identidad y consentimiento conforme al protocolo.", "Explica cada parte y facilita privacidad, comodidad y acompañamiento apropiado.", "Prepara los instrumentos y realiza las técnicas en la secuencia enseñada.", "Compara hallazgos de manera sistemática y detente ante molestias o cambios.", "Registra hallazgos objetivos y comunica los que requieran valoración."],
    precauciones: ["Realiza la práctica con supervisión y dentro del alcance de formación.", "Adapta la exploración a la condición y preferencias de la persona."],
    seguridad: ["Explica y solicita consentimiento; protege exposición corporal y privacidad.", "Aplica precauciones estándar y desinfecta los instrumentos reutilizables."],
    errores: ["Explorar sin explicar ni obtener consentimiento.", "Registrar interpretaciones como observaciones objetivas.", "Continuar pese al dolor sin reevaluar la situación."],
    evidencia: "Elabora un esquema de una valoración docente e identifica medidas de consentimiento, privacidad y registro objetivo."
  },
  {
    id: "mecanica-corporal",
    titulo: "Mecánica Corporal",
    unidad: "tecnicas",
    resumen: "Principios de postura, equilibrio y movimiento para proteger a la persona y al equipo de salud.",
    conceptos: ["Base de sustentación", "Alineación corporal", "Centro de gravedad", "Planificación y ayudas técnicas"],
    objetivo: "Relacionar los principios de mecánica corporal con la prevención de lesiones durante actividades de cuidado.",
    introduccion: "La mecánica corporal utiliza principios de alineación y equilibrio para reducir el esfuerzo. La valoración del riesgo y los equipos de asistencia tienen prioridad sobre levantar manualmente una carga.",
    materiales: ["Ayudas técnicas prescritas o autorizadas", "Calzado seguro y espacio despejado", "Apoyo de personal capacitado cuando se requiera"],
    pasos: ["Valora la tarea, el entorno y las capacidades de la persona.", "Solicita apoyo y utiliza la ayuda técnica apropiada.", "Organiza el espacio, despeja obstáculos y explica el movimiento.", "Mantén una base estable y evita giros bruscos o sobreesfuerzos.", "Detente y reevalúa si hay dolor, inseguridad o cambio inesperado."],
    precauciones: ["No levantes ni movilices a una persona sin evaluar riesgos y recibir entrenamiento.", "Sigue la evaluación de movilidad y el plan de asistencia individual."],
    seguridad: ["Usa dispositivos y número de asistentes definidos en el protocolo.", "Protege vías, líneas, privacidad y comunicación durante el movimiento."],
    errores: ["Intentar compensar una postura insegura levantando a pulso.", "Ignorar la capacidad variable de la persona o el entorno."],
    evidencia: "Analiza un caso de transferencia académica y propone cómo preparar espacio, equipo y apoyo antes de movilizar."
  },
  {
    id: "movilizacion-paciente",
    titulo: "Movilización del paciente",
    unidad: "tecnicas",
    resumen: "Planificación y asistencia segura de cambios de posición y traslados individualizados.",
    conceptos: ["Valoración de movilidad", "Transferencia y asistencia", "Ayudas técnicas", "Prevención de caídas"],
    objetivo: "Planificar una movilización académica identificando capacidades, riesgos, apoyo requerido y comunicación con la persona.",
    introduccion: "Movilizar incluye cambios posturales y traslados. Antes de ayudar, el equipo valora capacidades, condición, riesgos y equipo disponible; las decisiones se adaptan al plan de cuidado.",
    materiales: ["Ayuda técnica definida por la valoración", "Frenos y superficies en condición segura", "Personal de apoyo conforme al protocolo"],
    pasos: ["Consulta el plan de cuidado y valora la capacidad actual.", "Explica el movimiento y verifica comodidad y colaboración.", "Prepara frenos, espacio, calzado y ayuda técnica indicada.", "Coordina la maniobra con el equipo y conserva comunicación continua.", "Verifica alineación, comodidad y seguridad al finalizar; registra según protocolo."],
    precauciones: ["No continúes ante mareo, dolor, resistencia, cambios clínicos o equipo inadecuado.", "Solicita apoyo profesional cuando la asistencia segura no pueda realizarse con los recursos disponibles."],
    seguridad: ["Aplica prevención de caídas y lineamientos institucionales.", "Evita tracciones de extremidades, dispositivos y accesos."],
    errores: ["Omitir la valoración previa o no coordinar el movimiento.", "Dejar frenos sin accionar o el entorno con obstáculos."],
    evidencia: "Presenta una lista de comprobación previa a una movilización docente y justifica cuándo detener y pedir ayuda."
  },
  {
    id: "posiciones-paciente",
    titulo: "Posiciones del paciente",
    unidad: "tecnicas",
    resumen: "Alineación y apoyo postural según comodidad, valoración y objetivos del cuidado.",
    conceptos: ["Alineación", "Supina, lateral y otras posiciones enseñadas", "Puntos de presión", "Tolerancia y reevaluación"],
    objetivo: "Identificar consideraciones de seguridad, comodidad y alineación al seleccionar y mantener una posición indicada.",
    introduccion: "Las posiciones se eligen según objetivos de cuidado, condición, indicación y tolerancia. No existe una posición adecuada para todas las personas; la piel y la comodidad deben reevaluarse.",
    materiales: ["Almohadas y apoyos apropiados", "Superficie de soporte disponible", "Ayuda para movilización cuando se indique"],
    pasos: ["Consulta el objetivo del posicionamiento y valora comodidad, movilidad y riesgos.", "Explica el cambio de posición y reúne apoyos.", "Coloca a la persona con asistencia segura y alineación confortable.", "Comprueba respiración, comodidad, piel expuesta a presión y seguridad.", "Registra y reevalúa según el plan individual."],
    precauciones: ["Individualiza apoyos y frecuencia de reevaluación según el plan de cuidado.", "Evita posiciones que comprometan indicaciones clínicas conocidas."],
    seguridad: ["Solicita apoyo para movimientos con riesgo.", "Protege articulaciones, dispositivos y privacidad; activa medidas de prevención de caídas."],
    errores: ["Mantener una posición sin reevaluar comodidad o piel.", "Colocar apoyos de forma que compriman dispositivos o extremidades."],
    evidencia: "Explica qué valorarías antes y después de colocar a una persona en una posición de práctica."
  },
  {
    id: "higiene-paciente",
    titulo: "Higiene del paciente",
    unidad: "tecnicas",
    resumen: "Apoyo individualizado en higiene, confort, autonomía y cuidado de la piel.",
    conceptos: ["Autonomía y preferencias", "Privacidad", "Higiene de manos y precauciones", "Observación de piel"],
    objetivo: "Planificar apoyo de higiene que respete la autonomía y privacidad e incorpore medidas de seguridad y observación.",
    introduccion: "Las intervenciones de higiene favorecen comodidad y pueden apoyar la observación. Se adaptan a preferencias, capacidades, condición y protocolos; la persona participa en lo que puede realizar por sí misma.",
    materiales: ["Elementos de higiene acordes con las preferencias y protocolo", "Ropa y toallas limpias", "Equipo de protección según valoración"],
    pasos: ["Valora necesidades, capacidades, preferencias y riesgos.", "Explica la actividad, promueve participación y prepara privacidad y materiales.", "Aplica higiene de manos y medidas de control de infecciones.", "Brinda asistencia respetuosa de la secuencia indicada, manteniendo cubierta a la persona.", "Observa piel y tolerancia; comunica cambios relevantes.", "Deja a la persona segura, cómoda y con objetos necesarios al alcance."],
    precauciones: ["Adapta el método y temperatura del agua a la condición y política local.", "Suspende y busca orientación ante dolor, mareo, irritación o deterioro observado."],
    seguridad: ["Previene caídas y exposición; comprueba estabilidad y agua antes de iniciar.", "Respeta consentimiento, dignidad, privacidad y preferencias."],
    errores: ["Realizar la actividad sin preguntar o dejar a la persona expuesta.", "Omitir higiene de manos o dejar el entorno húmedo y resbaladizo."],
    evidencia: "Diseña un plan de apoyo de higiene que describa privacidad, autonomía, seguridad y observación."
  },
  {
    id: "admision-paciente",
    titulo: "Admisión del paciente",
    unidad: "continuidad",
    resumen: "Recepción segura y respetuosa, recopilación inicial de datos y orientación sobre la unidad.",
    conceptos: ["Identificación", "Entrevista inicial", "Conciliación y comunicación según función", "Orientación y registro"],
    objetivo: "Describir elementos de una admisión que favorezcan identificación, comunicación, orientación y continuidad de la atención.",
    introduccion: "La admisión inicia la relación de cuidado en una unidad o servicio. Incluye verificación de identidad, escucha, recopilación de datos conforme a la función profesional y orientación sobre el entorno.",
    materiales: ["Formato institucional de ingreso", "Medios autorizados para verificar identidad", "Material informativo de la unidad"],
    pasos: ["Saluda, presenta tu función y explica el proceso.", "Verifica identidad con los identificadores institucionales establecidos.", "Escucha necesidades inmediatas y comunica al profesional responsable los hallazgos pertinentes.", "Orienta sobre la unidad, timbre de llamado, privacidad y rutinas aplicables.", "Registra información objetiva conforme al formato y políticas locales."],
    precauciones: ["Limita el acceso y la conversación sobre datos sensibles.", "Respeta la participación de la persona y el proceso de consentimiento aplicable."],
    seguridad: ["Confirma la identidad usando identificadores aprobados, no solo habitación o apariencia.", "Notifica riesgos o necesidades urgentes por el canal institucional."],
    errores: ["Asumir que un brazalete o una habitación bastan para identificar.", "Omitir orientación o registrar información no confirmada."],
    evidencia: "Elabora un guion de bienvenida y una lista de verificación de ingreso sin utilizar datos reales."
  },
  {
    id: "alta-paciente",
    titulo: "Alta del paciente",
    unidad: "continuidad",
    resumen: "Preparación de la transición de cuidado, comunicación y verificación de comprensión según el rol.",
    conceptos: ["Continuidad asistencial", "Instrucciones autorizadas", "Red de apoyo", "Registro y derivación"],
    objetivo: "Identificar elementos educativos y de coordinación de una transición segura de atención.",
    introduccion: "El alta es una transición que requiere coordinación entre la persona, su red de apoyo y el equipo de salud. La información se adapta a instrucciones autorizadas, necesidades de comprensión y procedimientos locales.",
    materiales: ["Plan e instrucciones de alta autorizadas", "Material educativo validado", "Formato institucional de continuidad"],
    pasos: ["Confirma el plan de alta con el equipo responsable.", "Identifica necesidades de orientación y preferencias de comunicación.", "Entrega o refuerza la información aprobada dentro del alcance de tu función.", "Invita a la persona a explicar con sus palabras los siguientes pasos importantes.", "Confirma que las dudas se canalicen al profesional indicado y documenta según política."],
    precauciones: ["No modifiques tratamiento ni instrucciones prescritas.", "Adapta comunicación, idioma y apoyos a las necesidades identificadas."],
    seguridad: ["Verifica comprensión de citas, señales de alarma autorizadas y contactos institucionales.", "Asegura continuidad de dispositivos, pertenencias e información conforme a política."],
    errores: ["Dar instrucciones contradictorias o no autorizadas.", "Confundir entrega de un documento con comprensión efectiva."],
    evidencia: "Diseña una lista de verificación académica para reforzar comprensión durante una transición de cuidado."
  },
  {
    id: "muestras-biologicas",
    titulo: "Muestras biológicas",
    unidad: "tecnicas",
    resumen: "Principios de identificación, integridad, manejo y traslado conforme al tipo de muestra y protocolo.",
    conceptos: ["Identificación de la persona y la muestra", "Tipo y recipiente", "Etiquetado", "Cadena de transporte"],
    objetivo: "Reconocer factores que mantienen la identificación e integridad de una muestra desde su obtención hasta su entrega.",
    introduccion: "La obtención y manejo de muestras depende del espécimen, la indicación, la competencia autorizada y el protocolo del laboratorio. La etiqueta correcta y la identificación segura son esenciales.",
    materiales: ["Orden o solicitud validada", "Recipiente y elementos establecidos para la muestra", "Equipo de protección y bolsa de transporte indicada"],
    pasos: ["Revisa solicitud, preparación e indicaciones del laboratorio.", "Verifica identidad con los métodos institucionales y explica el proceso.", "Obtén o recibe la muestra solo si tu rol y formación lo permiten.", "Etiqueta según el protocolo en el punto de obtención y conserva las condiciones requeridas.", "Transporta por la ruta institucional y documenta entrega o incidencias."],
    precauciones: ["Sigue instrucciones específicas de cada espécimen; no extrapoles técnicas.", "No proceses una muestra dudosa, sin etiqueta o con discrepancias; consulta al responsable."],
    seguridad: ["Usa precauciones estándar, recipiente compatible y embalaje requerido.", "Protege a la persona, al personal y a la comunidad durante la manipulación."],
    errores: ["Etiquetar lejos de la persona o antes de confirmar identidad.", "Ignorar condiciones de conservación o cadena de transporte."],
    evidencia: "Crea un diagrama de flujo académico para identificación, etiquetado, transporte y notificación de incidencias."
  },
  {
    id: "rpbi",
    titulo: "RPBI",
    unidad: "tecnicas",
    resumen: "Separación y manejo seguro de residuos peligrosos biológico-infecciosos según normativa aplicable.",
    conceptos: ["Identificación y segregación", "Contenedores autorizados", "Precauciones estándar", "Normativa local"],
    objetivo: "Explicar por qué el manejo de RPBI depende de una clasificación correcta y del cumplimiento de la regulación y el protocolo vigentes.",
    introduccion: "Los residuos con riesgo biológico deben manejarse de forma que proteja a personas y ambiente. Las definiciones, recipientes, etiquetado y disposición final dependen de la regulación aplicable y las reglas institucionales.",
    materiales: ["Contenedores autorizados y etiquetados", "Equipo de protección según riesgo", "Procedimiento institucional actualizado"],
    pasos: ["Identifica el residuo conforme a la clasificación vigente.", "Consulta el contenedor y nivel de llenado permitidos.", "Segrega el material en el punto de generación, sin compactarlo ni manipularlo innecesariamente.", "Cierra, etiqueta y traslada únicamente por la ruta autorizada.", "Notifica incidentes o derrames según el plan institucional."],
    precauciones: ["Esta guía no sustituye la normativa vigente en tu país ni el programa institucional.", "No deposites un residuo si existe duda de clasificación: consulta al responsable de seguridad."],
    seguridad: ["Evita reencapuchar, compactar o introducir manualmente material en recipientes.", "Usa contenedores sin sobrepasar límites y notifica exposición de inmediato."],
    errores: ["Segregar por costumbre sin verificar la clasificación.", "Usar contenedores incorrectos, dañados o sobrellenados."],
    evidencia: "Construye una tabla comparativa basada en la norma y protocolo vigentes de tu institución, con fuente y fecha."
  },
  {
    id: "carro-curaciones",
    titulo: "Carro de curaciones",
    unidad: "tecnicas",
    resumen: "Organización, verificación y limpieza del carro para apoyar técnicas asépticas según protocolo.",
    conceptos: ["Disponibilidad y organización", "Integridad y vigencia", "Limpieza", "Técnica aséptica"],
    objetivo: "Describir una revisión académica del carro de curaciones que preserve organización, limpieza e integridad de insumos.",
    introduccion: "El carro de curaciones reúne materiales utilizados en procedimientos definidos. Su organización concreta corresponde al servicio; las comprobaciones y la limpieza siguen la frecuencia y política institucional.",
    materiales: ["Lista de verificación local", "Material e insumos aprobados por el servicio", "Productos de limpieza indicados"],
    pasos: ["Consulta la lista de verificación del servicio y realiza higiene de manos.", "Inspecciona orden, limpieza, integridad de paquetes y fechas según política.", "Repón faltantes con insumos autorizados y mantén la separación establecida.", "Desinfecta superficies conforme a instrucciones del producto y protocolo.", "Registra la verificación e informa discrepancias al responsable."],
    precauciones: ["No uses material vencido, abierto, húmedo o con empaque comprometido.", "No cambies la organización institucional sin autorización."],
    seguridad: ["Conserva superficies limpias y elementos estériles protegidos.", "Usa químicos con el equipo de protección indicado y nunca mezcles productos."],
    errores: ["Reponer sin revisar empaque o caducidad.", "Confundir limpieza del carro con esterilidad del material."],
    evidencia: "Diseña una lista de revisión del carro basada en el protocolo del servicio e incluye un espacio para reportar incidencias."
  },
  {
    id: "limpieza-desinfeccion",
    titulo: "Limpieza y desinfección",
    unidad: "tecnicas",
    resumen: "Principios de limpieza de superficies y equipos y uso seguro de productos autorizados.",
    conceptos: ["Limpieza", "Desinfección", "Tiempo de contacto", "Compatibilidad de materiales"],
    objetivo: "Distinguir la limpieza de la desinfección y reconocer condiciones de uso seguro de un producto conforme a su etiqueta y protocolo.",
    introduccion: "La limpieza retira suciedad y materia orgánica; la desinfección reduce microorganismos según el producto y el uso previsto. Las instrucciones del fabricante y del programa institucional definen aplicación y tiempo de contacto.",
    materiales: ["Producto institucional autorizado", "Instrucciones del fabricante", "Paños y equipo de protección según protocolo"],
    pasos: ["Identifica superficie o equipo y consulta el producto compatible.", "Prepara materiales y equipo de protección indicados.", "Retira suciedad mediante el método establecido antes de desinfectar, cuando corresponda.", "Aplica el producto y respeta concentración e indicaciones de etiqueta.", "Mantén el tiempo de contacto especificado y registra según política."],
    precauciones: ["No mezcles productos ni trasvases sin etiquetado y autorización.", "Respeta ventilación, compatibilidad, almacenamiento y vencimiento."],
    seguridad: ["Sigue la ficha y etiqueta del producto y el protocolo institucional.", "Reporta exposición accidental conforme al plan de seguridad."],
    errores: ["Secar el producto antes del tiempo indicado.", "Usar un producto en una superficie no compatible.", "Confundir limpieza con desinfección."],
    evidencia: "Compara la etiqueta de un producto autorizado con un protocolo local y resume sus indicaciones de seguridad."
  },
  {
    id: "seguridad-paciente",
    titulo: "Principios básicos de seguridad del paciente",
    unidad: "fundamentos",
    resumen: "Prácticas para prevenir daño, reconocer riesgos y fomentar comunicación y aprendizaje del sistema.",
    conceptos: ["Identificación", "Comunicación efectiva", "Prevención de infecciones y caídas", "Cultura de seguridad", "Notificación"],
    objetivo: "Identificar prácticas generales de seguridad del paciente y explicar cuándo detenerse, verificar o escalar una preocupación.",
    introduccion: "La seguridad del paciente es responsabilidad compartida y requiere sistemas de trabajo confiables, comunicación abierta y aprendizaje de incidentes. Los protocolos locales detallan prácticas específicas.",
    materiales: ["Políticas institucionales de seguridad", "Lista de verificación aplicable", "Canal de comunicación y reporte local"],
    pasos: ["Identifica riesgos del entorno y de la tarea antes de intervenir.", "Verifica identidad y propósito usando el proceso vigente.", "Comunica información relevante de forma clara y confirma los mensajes críticos.", "Aplica precauciones de prevención pertinentes al riesgo.", "Notifica errores, incidentes o condiciones inseguras según la política."],
    precauciones: ["Consulta a una persona supervisora ante dudas, discrepancias o falta de competencia.", "Aplica protocolos actuales y evita basarte solo en memoria o supuestos."],
    seguridad: ["Fomenta comunicación respetuosa, participación de la persona y notificación sin demora.", "Ante una situación insegura, pausa y solicita apoyo por los canales establecidos."],
    errores: ["Normalizar omisiones o no comunicar un cambio relevante.", "Culpar a una persona sin examinar factores del sistema.", "Omitir verificación por prisa o familiaridad."],
    evidencia: "Analiza una situación hipotética de riesgo e identifica factores, acción inmediata, comunicación y aprendizaje preventivo."
  }
];

window.UO_ASIGNATURAS = [
  {
    id: "fundamentos-enfermeria-i",
    titulo: "Fundamentos de Enfermería I",
    descripcion: "Asignatura inicial con 17 módulos, guías académicas, procedimientos y autoevaluación.",
    estado: "Disponible",
    href: "#fundamentos"
  },
  {
    id: "nuevas-asignaturas",
    titulo: "Más asignaturas",
    descripcion: "La plataforma está organizada para incorporar nuevos cursos y recursos en futuras etapas.",
    estado: "Espacio preparado",
    href: "#acerca"
  }
];
